"""
memory_service.py

Conversation memory manager for VoxAgent AI.

Responsibilities
----------------
- Store recent conversation turns
- Maintain a rolling long-term summary
- Limit prompt growth
- Support multiple concurrent sessions

No AI model is loaded here.
The summary itself is generated by groq_service.update_memory_summary().
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from typing import Dict, List

from app.services.groq_service import update_memory_summary


# Number of most recent turns kept verbatim
MAX_RECENT_TURNS = 10

# After this many turns leave the recent window,
# summarize them into long_term_summary.
SUMMARY_BATCH_SIZE = 6


@dataclass
class ConversationMemory:

    recent_turns: deque = field(
        default_factory=lambda: deque(maxlen=MAX_RECENT_TURNS)
    )

    long_term_summary: str = ""

    def add_turn(
        self,
        speaker: str,
        message: str,
    ) -> None:
        """
        Add a conversation turn.

        Stored format is standardized across the project.

        {
            "speaker": "...",
            "text": "..."
        }
        """

        self.recent_turns.append(
            {
                "speaker": speaker,
                "text": message.strip(),
            }
        )

    def history(self) -> List[Dict]:
        """
        Return recent turns.
        """

        return list(self.recent_turns)

    def clear(self):

        self.recent_turns.clear()

        self.long_term_summary = ""

    def maybe_refresh_summary(self):
        """
        Refresh rolling summary.

        If enough turns have accumulated,
        summarize the oldest half while
        keeping the newest turns verbatim.
        """

        if len(self.recent_turns) < MAX_RECENT_TURNS:
            return

        turns = list(self.recent_turns)

        old_turns = turns[:SUMMARY_BATCH_SIZE]

        new_turns = turns[SUMMARY_BATCH_SIZE:]

        try:

            updated = update_memory_summary(

                existing_summary=self.long_term_summary,

                new_turns=old_turns,

            )

            if updated:

                self.long_term_summary = updated

                self.recent_turns = deque(

                    new_turns,

                    maxlen=MAX_RECENT_TURNS,

                )

        except Exception:

            # Never break the conversation
            pass


class MemoryManager:

    def __init__(self):

        self.sessions: Dict[str, ConversationMemory] = {}

    def get(
        self,
        session_id: str,
    ) -> ConversationMemory:

        if session_id not in self.sessions:

            self.sessions[session_id] = ConversationMemory()

        return self.sessions[session_id]

    def add_turn(
        self,
        session_id: str,
        speaker: str,
        message: str,
    ):

        memory = self.get(session_id)

        memory.add_turn(

            speaker=speaker,

            message=message,

        )

        memory.maybe_refresh_summary()

    def history(
        self,
        session_id: str,
    ):

        return self.get(session_id).history()

    def summary(
        self,
        session_id: str,
    ):

        return self.get(session_id).long_term_summary

    def clear(
        self,
        session_id: str,
    ):

        if session_id in self.sessions:

            del self.sessions[session_id]

    def active_sessions(self):

        return list(self.sessions.keys())

    def session_count(self):

        return len(self.sessions)


memory_manager = MemoryManager()